---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-config
  namespace: kube-system
data:
  # You must set a non-zero value for Typha replicas below.
{{- if .Values.config.typha.enabled }}
  typha_service_name: "calico-typha"
{{- else }}
  typha_service_name: "none"
{{- end }}
  # Configure the Calico backend to use.
  calico_backend: "{{ .Values.config.backend }}"

  # Configure the MTU to use for workload interfaces and tunnels.
  # By default, MTU is auto-detected, and explicitly setting this field should not be required.
  # You can override auto-detection by providing a non-zero value.
  veth_mtu: "{{ .Values.config.veth_mtu }}"

  # The CNI network configuration to install on each node. The special
  # values in this config will be automatically populated.

  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "error",
          "log_file_path": "/var/log/calico/cni/cni.log",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
        {{- if ne .Values.config.ipv6.autoDetectionMethod "none" }}
          "ipam": {
            "type": "calico-ipam",
            "assign_ipv4": "false",
            "assign_ipv6": "true"
          },
        {{- end }}
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }
